### ISSUE TITLE
tags are not working as expected

### ISSUE THREAD

**Issue by jaywryan** [RedHatInsights/ansible-collections-insights#22]
Managing tags doesn't work as expected.

1. Simply including the role without specifying any tags, executes a tag removal.  which will delete the tags.yaml file from the client.  Perhaps this option should be explicit to remove existing tags if no `insights_tags` variable is specified
``` shell
# example task
tasks:
  - include_role:
      name: redhat.insights.insights_client
# output
TASK [redhat.insights.insights_client : Deploy Custom Tags] ****************************************************************************
skipping: [satellite] => {"changed": false, "skip_reason": "Conditional result was False"}
skipping: [tower] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [redhat.insights.insights_client : Remove Tags] ***********************************************************************************
ok: [satellite] => {"changed": false, "path": "/etc/insights-client/tags.yaml", "state": "absent"}
changed: [tower] => {"changed": true, "path": "/etc/insights-client/tags.yaml", "state": "absent"}
```
2.  Deleting the tags has no effect in insights, tags are removed from the client but there is no mechanism to remove the tags in insights itself.  I believe this is a bug/feature in Insights, this option should be removed from the role until this actually works in insights itself. https://github.com/RedHatInsights/ansible-collections-insights/blob/1b455fa7ba76fecc3d69658a83adeb83b056f9f5/roles/insights_client/tasks/main.yml#L75-L79

**Comment by ptoscano** [comment]
The preferred Ansible way to connect Red Hat system to RHSM and Insights is the "rhc" system role [1]. New use cases & features related to the connection of a system to Insights should be implemented there. As of the release of version 1.3.0, the bits related to insights-client are officially deprecated. 

As for this issue: while this is a valid issue, it has not been addressed in a long time, and properly fixing this means changing the API in a potentially incompatible way. Since "tags" work fine already in the "rhc" role, the strong recommendation is to switch to that.

Hence, I'm closing this issue as "wontfix". Thanks anyway for the report.

[1] https://github.com/linux-system-roles/rhc/
